/**
 * Practice: Pass values between functions
 *
 * - Create two functions
 * - Main function creates article element with data from object
 * - Helper function creates.
 */
const pardhu = {
  fullName: "Pardha Saradhi Chodey",
  gender: "Male",
  height: 175,
  weight: 98,
};
function add() {
  const content = `<h1>About Me</h1>
    <h3>Name:${pardhu.fullName}</h3>
    <h3>Gender:${pardhu.gender}</h3>
    <h3>Height:${pardhu.height}</h3>
    <h3>Weight:${pardhu.weight}</h3>`;
  const article = document.createElement("article");
  article.innerHTML = content;
  const main = document.querySelector("main");
  main.append(article);
}
add();
const sec = function (text) {
  const content = `
  <p>${text}</p>
  <h1>About Me</h1>
      <h3>Name:${pardhu.fullName}</h3>
      <h3>Gender:${pardhu.gender}</h3>
      <h3>Height:${pardhu.height}</h3>
      <h3>Weight:${pardhu.weight}</h3>`;
  const article = document.createElement("article");
  article.innerHTML = content;
  const main = document.querySelector("main");
  main.append(article);
};
sec("this is generated by constant function");
